# lines marked with a *required* are REQUIRED PIECES OF METADATA
# if a header does not have *required* it is not required info,
# but part of its metadata can be marked as *required* to indicate
# that this metadata is required when the header is included
name = "" # *required* name of model run
version = "" # version of model code
description = [ "",] # description/purpose of the model run
assumptions = [ "",] # model specific assumptions for this run
notes = [ "",]

[config]
param1 = "" # any info on config for model sim

[source_code]
location = "" # *required* Location of the source code
branch = "" # Branch that will be used
tag = "" # The git tag of source code
image = "" # The location of container image

[env_deps]
package = "version" # Location to record environmental dependencies. Not required.

[[datasets]]
name = "" # ** name of dataset
description = [ "",] # any info about dataset
scheduled_checkin = "" # estimate of when datset will be checked in

[[tasks]]
id = "" # *required* name to refer to this task, must be unique in this toml
description = "" # *required*
inputs = [ "",]
notes = [ "",]
scheduled_start = "" # optional, by default this is scheduled accoring to model run and handoff schedules
scheduled_end = "" # optional, by default this is scheduled accoring to model run and handoff schedules
assignee = "" # *required*, username for the person that will be assigned this task
handoff_id = "" # optional, add a handoff_id here if this task is associated with a handoff
[[tasks.acceptance_criteria]]
bounds = [] # These are just examples and are not required.
columns = [ "",]
units = ""


[[tasks]]
id = "" # *required* name to refer to this task, must be unique in this toml
description = "" # *required*
inputs = [ "",]
notes = [ "",]
scheduled_start = "" # optional, by default this is scheduled accoring to model run and handoff schedules
scheduled_end = "" # optional, by default this is scheduled accoring to model run and handoff schedules
assignee = "" # *required*, username for the person that will be assigned this task
handoff_id = "" # optional, add a handoff_id here if this task is associated with a handoff
[[tasks.parameters]]
type = "line" # These are just examples are not required.
columns = []
colors = []


