name = "team102"  # A short team name, lowercase letters and numbers only.

description = "This is a test team"  # A short team description.

[[members]]  # Remove if no such members
email = "user1@example.com"
first_name = ""
last_name = ""
organization = ""

[[members]]  # Remove if no such members
email = "user2@example.com"
first_name = ""
last_name = ""
organization = ""
