
[user]
name = "No Lie"
email = "no.lie@nrel.gov"
[project]
    name = "project_abcd" # the name users give to refer to this project in pipes
    password = "pipesRocks" # for modelers to hook into the pipeline at the start of the project
[model]
    name = "capex"
    type = "RPM"
    uuid = "some uuid generated when model was initialized"
    version = ""
    config = ""
    deps = [""]
    notes = ""








