# this is an example of the toml that is submitted WHEN A USER HAS COMPLETED TASKS AND WANTS TO NOTIFY PIPES

task_name = ""             # *required* must be unique
type = "Transformation"    # *required* must be one of [QAQC, Visualization, Transformation]
dataset_ids = []           # *optional* This is for datasets that live within the model run
vertex_ids = []            # *optional* If any datasets live outside of this model run, provide the vertex ids here
description = ""           # *required* describe the purpose of the task
notes = ""			           # any info to store about the task (e.g., any issues etc.)
script = []                # the script used, provide the full path relative to the toml file
subtask_ids = []			     # if performing preset tasks that PIPES knows about (e.g., transformations),
                           # please provide all ids of the tasks that were performed
						               # to get a list of possible task ids, in the terminal type `some PIPES CLI command`
relates_to = []            # objects in PIPES this task relates to

[outputs]                  # optional
  location = ""            # where is the output located if it is not going to be checked into PIPES
  # put any other information related to outputs below